"""meow

Revision ID: 7a037b92ae7c
Revises: 43f0bf77bf97
Create Date: 2020-09-28 14:35:44.860582
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7a037b92ae7c'
down_revision = '43f0bf77bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'participants',
        sa.Column('foo', sa.String(), server_default='bar', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'foo')
    # ### end Alembic commands ###
